### ISSUE TITLE
Disable zabbix-agent per default

### ISSUE THREAD

**Issue by DennisGaida** [tiredofit/docker-traefik-cloudflare-companion#74]
**Description of the feature**
The Zabbix-Agent comes with this container as your base image (https://github.com/tiredofit/docker-alpine) configures this.

The problem with this base-implementation is that **this** container makes DNS requests for `zabbix-agent` every minute. This is spamming the DNS server and actually unnecessary in an environment without Zabbix.

I was able to disable zabbix via `CONTAINER_ENABLE_MONITORING: "FALSE"` environment variable and believe this should be the default or better documented in this container (since I had to dig out the base image to find this variable). Or: The default zabbix config could be to not do a DNS request for `zabbix-agent` every minute?

**Benftits of feature**
No more `zabbix-agent` DNS spam

**Comment by tiredofit** [comment]
Thanks, Since my clients and I are the primary user of these images I leave Zabbix Agent by default on. I feel my README is [descriptive enough](https://github.com/tiredofit/docker-traefik-cloudflare-companion/blob/master/README.md#base-images-used) that there are other options that may or may not need to be configured.

I unfortunately don't know much about changing the interval that the DNS request is being made for, but it sounds like you have resolved with the environment variable to disable entirely, which I feel is a better approach to save on resources. Going to close this on that basis.

**Comment by Distortedlogic** [comment]
there isnt even any code in the repo that references zabbix .. so that means there is private code somewhere that u are using? seriously wtf is this bullshit? this has to be malicious given u have not done anything to fix, hide the code that installs the agent such that we dont even know how it is being used much less given a way to disable it. you have a huge list of ENV VARs but putting in one more to disable zabbix on the user system is too much? NAH THIS IS MALICIOUS!!!
